### ISSUE TITLE
No cancel button on edit page

### ISSUE THREAD

**Issue by ddbruce** [wtg/ambulance#2]
![image](https://cloud.githubusercontent.com/assets/5694673/10500954/a6a47fae-72aa-11e5-8d47-60d11f713614.png)

**Comment by TManzini** [comment]
My goodness, does this have its own mailing list...

Tom


--

*Thomas Manzini*
Computer Science
Rensselaer Polytechnic Institute
Class of 2016
Email: Tom.M@nzini.com <tom.m@nzini.com>
Phone: (702) 324-4319

**Comment by ddbruce** [comment]
My goodness, I'll fix that

**Comment by ddbruce** [comment]
It goes out to everyone who is on the team. You can change your settings 
on GitHub.


DB



On 15 Oct 2015 00:38, TManzini wrote:
> My goodness, does this have its own mailing list...
>
> Tom
>
>
> --
>
> *Thomas Manzini*
> Computer Science
> Rensselaer Polytechnic Institute
> Class of 2016
> Email: Tom.M@nzini.com <tom.m@nzini.com>
> Phone: (702) 324-4319
>
> On Wed, Oct 14, 2015 at 7:35 PM, Dan Bruce <notifications@github.com> 
> wrote:
>
> > [image: image]
> > 
> <https://cloud.githubusercontent.com/assets/5694673/10500954/a6a47fae-72aa-11e5-8d47-60d11f713614.png>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wtg/RPI_Ambulance_Website/issues/2>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wtg/RPI_Ambulance_Website/issues/2#issuecomment-148279119>.
>

-- 
Daniel D. Bruce

dan@ddbruce.com <mailto:dan@ddbruce.com>
(508) 688-5830

************************
This email and any files transmitted with it are private and 
confidential and are solely for the use of the addressee. It may contain 
material which is legally privileged. If you are not the addressee or 
the person responsible for delivering to the addressee, be advised that 
you have received this e-mail in error and that any use of it is 
strictly prohibited.
************************
