### ISSUE TITLE
Request Coverage "Select" buttons not responding

### ISSUE THREAD

**Issue by TManzini** [wtg/ambulance#27]
When clicked, the buttons labeled "select" below the different tiers do not respond.

**Comment by TManzini** [comment]
Was this duplicated with #52? I still see this behavior

**Comment by David-Sparky** [comment]
Justin fixed the issue a few days ago, but we haven't brought the change to the live version yet since we want the mail script to work before we give the option for a form. We don't want people to think they sent us a request because the form gives a success message, but not send us anything.

**Comment by justetz** [comment]
@TManzini, @David-Sparky, I am working on the email script right now. I can get a coming soon modal up in the mean time with directions to email the officer email for now, if you think that's necessary. It'll only be another day or so.

**Comment by TManzini** [comment]
Makes sense, thanks for the clarification

## 

_Thomas Manzini_
Computer Science
Rensselaer Polytechnic Institute
Class of 2016
Email: Tom.M@nzini.com tom.m@nzini.com
Phone: (702) 324-4319

**Comment by David-Sparky** [comment]
@justetz I don't really think we need to do that. The odds of someone giving us an event right now are fairly low, so keeping it offline/unresponsive works for the time-being.
