### ISSUE TITLE
List Current Supervisors on Supervisor Page

### ISSUE THREAD

**Issue by TManzini** [wtg/ambulance#35]
The old site had the current list of supervisors on the supervisor page, lets do the same thing here.

Current supervisors are:
Nick Hopkins
Thomas Manzini
Jordan Williams

**Comment by David-Sparky** [comment]
We can totally do this, although it would be statically set for the time-being. Also is Brent still a DS?

**Comment by TManzini** [comment]
For now, thats ok.

Oops, my bad

Brent is indeed a DS still
