### ISSUE TITLE
Snow freezes when context changes on chrome

### ISSUE THREAD

**Issue by TManzini** [wtg/ambulance#42]
When you view a document or when you click on the google maps inlay the snow on the page stops falling. I expect this has something to do with the way that chrome handles active scripts when the context changes, but I haven't checked on other browsers.

**Comment by David-Sparky** [comment]
I just took a look at this and tried to recreate it using chrome, but was unable to do so. The only thing I've noticed is a slight hang when the page loading content for the first time in that session. It may have something to do with one of the features which pauses the snow if the window is not active.

**Comment by jcub** [comment]
Recreated on Version 47.0.2526.106 (64-bit) of chrome for os x 10.10.5; also Version 9.0.2 (10601.3.9) of safari.

Appears to hang when view is not the original view (i.e., navigate to contact us from home then click on the map)
Navigation straight to contact us page then click on map results in no problems. I know chrome stops js on pages it thinks are in the background. 

Keep up the hard work! New site looks good.

**Comment by David-Sparky** [comment]
I just pushed a change to the repo and the live site. It should resolve the issue. Let me know if it works and we can close it. :)

**Comment by jcub** [comment]
It works as far as I can tell
