### ISSUE TITLE
URGENT -- THE SNOW IS GONE

### ISSUE THREAD

**Issue by TManzini** [wtg/ambulance#61]

**Comment by jcub** [comment]
It's going to be 56 tomorrow. Maybe rain would be more appropriate.

On a possibly related note there are two TypeErrors appearing in console

isotope.js:55  Uncaught TypeError: Cannot read property 'Item' of undefined
(anonymous function) @ isotope.js:55
(anonymous function) @ isotope.js:60

plugin-config.js:22 Uncaught TypeError: $portfolio.isotope is not a function
(anonymous function) @ plugin-config.js:22
n.event.dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
